### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'json'

### ISSUE THREAD

**Issue by SalikovAlex** [iamale/rock#12]
File "/Users/salik/.virtualenvs/rocket/lib/python3.5/site-packages/rock_cli/cli.py", line 97, in register
    id = r.json()["sms_verification"]["id"]
AttributeError: 'NoneType' object has no attribute 'json'

**Comment by notpushkin** [comment]
Разобрался. Уже исправлено в master, забыл зарелизить. Сейчас будет.

**Comment by notpushkin** [comment]
Можете на 0.3.1 проверить? Уже лежит в PyPI.
